export const els = {
  currentQ: document.getElementById("current-q"),
  totalQ: document.getElementById("total-q"),
  scoreCorrect: document.getElementById("score-correct"),
  scoreWrong: document.getElementById("score-wrong"),
  progressBar: document.getElementById("progress-bar"),
  qNumber: document.getElementById("q-number"),
  qType: document.getElementById("q-type"),
  qText: document.getElementById("q-text"),
  optionsList: document.getElementById("options-list"),
  checkBtn: document.getElementById("check-btn"),
  nextBtn: document.getElementById("next-btn"),
  quizArea: document.getElementById("quiz-area"),
  resultsArea: document.getElementById("results-area"),
  finalScore: document.getElementById("final-score"),
  finalMessage: document.getElementById("final-message"),
  globalShuffleBtn: document.getElementById("global-shuffle-btn"),
  restartBtn: document.getElementById("global-restart-btn"),
  questionCard: document.getElementById("question-card"),
  restartResultsBtn: document.getElementById("restart-results-btn"),
  shuffleResultsBtn: document.getElementById("shuffle-results-btn"),
};
