export const els = {
  currentQ: document.getElementById('current-q')! as HTMLElement,
  totalQ: document.getElementById('total-q')! as HTMLElement,
  scoreCorrect: document.getElementById('score-correct')! as HTMLElement,
  scoreWrong: document.getElementById('score-wrong')! as HTMLElement,
  progressBar: document.getElementById('progress-bar')! as HTMLElement,
  qNumber: document.getElementById('q-number')! as HTMLElement,
  qType: document.getElementById('q-type')! as HTMLElement,
  qText: document.getElementById('q-text')! as HTMLElement,
  optionsList: document.getElementById('options-list')! as HTMLElement,
  checkBtn: document.getElementById('check-btn')! as HTMLButtonElement,
  nextBtn: document.getElementById('next-btn')! as HTMLElement,
  quizArea: document.getElementById('quiz-area')! as HTMLElement,
  resultsArea: document.getElementById('results-area')! as HTMLElement,
  finalScore: document.getElementById('final-score')! as HTMLElement,
  finalMessage: document.getElementById('final-message')! as HTMLElement,
  globalShuffleBtn: document.getElementById('global-shuffle-btn')! as HTMLElement,
  restartBtn: document.getElementById('global-restart-btn')! as HTMLElement,
  questionCard: document.getElementById('question-card')! as HTMLElement,
  restartResultsBtn: document.getElementById('restart-results-btn')! as HTMLElement,
  shuffleResultsBtn: document.getElementById('shuffle-results-btn')! as HTMLElement,
};
